//! H2: pin the Kamino `Reserve` struct layout we rely on.
//!
//! `kamino-lend = "=0.4.1"` in Cargo.toml stops silent crate upgrades, and
//! `update_rate_index` re-checks `reserve.liquidity.mint_pubkey` at runtime
//! against the market's expected mint. This offline test is the third
//! layer: if a crate bump or manual edit ever changes the `Reserve` struct
//! size or the offsets we read, the assertions below fail in CI before the
//! bad bytecode ever reaches devnet. When that happens, re-validate the
//! offsets in `helpers/kamino.rs::read_kamino_rate_index` against the new
//! Kamino layout.

use std::mem::size_of;

use kamino_lend::state::Reserve;

/// Size of `kamino_lend::state::Reserve` as generated by `anchor-gen` at the
/// pinned kamino-lend = 0.4.1. The on-chain fixture is 11_500 bytes (11_492
/// after the 8-byte Anchor discriminator) because Kamino keeps a large
/// `reserved_[...]` tail for future extensions — the generated Rust struct
/// doesn't materialize those padding bytes, so the actual Rust size is
/// smaller. What matters for our reads is that the prefix containing
/// `liquidity.mint_pubkey`, `liquidity.cumulative_borrow_rate_bsf`, and
/// `last_update.slot` stays stable. Any crate bump that changes this size
/// is a signal to re-validate `helpers/kamino.rs::read_kamino_rate_index`
/// against the new layout before allowing the build.
const EXPECTED_RESERVE_SIZE: usize = 8_656;

#[test]
fn reserve_struct_size_matches_pinned_crate() {
    let actual = size_of::<Reserve>();
    assert_eq!(
        actual, EXPECTED_RESERVE_SIZE,
        "Reserve struct size changed from {EXPECTED_RESERVE_SIZE} to {actual}. \
         Either the kamino-lend crate was bumped (check Cargo.toml pin) or \
         the crate's layout shifted. Re-validate every field access in \
         helpers/kamino.rs and update EXPECTED_RESERVE_SIZE here."
    );
}
